// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ8rRMT57EBZfBBgV7C3HihR2ik2SNlI8',
    appId: '1:751987947078:web:21c400d41968a2f0c27c47',
    messagingSenderId: '751987947078',
    projectId: 'docplan22-87323',
    authDomain: 'docplan22-87323.firebaseapp.com',
    storageBucket: 'docplan22-87323.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmTyL5LzrJqmcOhdOpuZqESS438bxkClQ',
    appId: '1:751987947078:android:d64a2b6a6b291f19c27c47',
    messagingSenderId: '751987947078',
    projectId: 'docplan22-87323',
    storageBucket: 'docplan22-87323.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBdjbrGULK5DSNRJuvLGvfGD65Y8_3q6g',
    appId: '1:751987947078:ios:ad55eba0f7236240c27c47',
    messagingSenderId: '751987947078',
    projectId: 'docplan22-87323',
    storageBucket: 'docplan22-87323.firebasestorage.app',
    iosBundleId: 'com.example.docplan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBdjbrGULK5DSNRJuvLGvfGD65Y8_3q6g',
    appId: '1:751987947078:ios:ad55eba0f7236240c27c47',
    messagingSenderId: '751987947078',
    projectId: 'docplan22-87323',
    storageBucket: 'docplan22-87323.firebasestorage.app',
    iosBundleId: 'com.example.docplan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ8rRMT57EBZfBBgV7C3HihR2ik2SNlI8',
    appId: '1:751987947078:web:3dc7a680a986474dc27c47',
    messagingSenderId: '751987947078',
    projectId: 'docplan22-87323',
    authDomain: 'docplan22-87323.firebaseapp.com',
    storageBucket: 'docplan22-87323.firebasestorage.app',
  );
}
